# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8265991a1369f84273fd35ff84a2c4b3b5c5e6b5eb185e0641eea28deb4b78c58a08e965117effedd832d7dbdf3a6b64a9331523e023d0d4da417b32964d50b2

test:
  secret_key_base: 78791a3d1e2dc4b58990ac7ac8606aa9667f37180cb1a65a01fa69a45faa62259fa031de4a5e0e794adc504810c9275825a1c750d6834eba0a0460fa6b2d8c3a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
